import React, { memo, useCallback } from 'react';

import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import FileDownloadIcon from '@mui/icons-material/FileDownload';
import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import { Box, IconButton, Tooltip, Typography, useTheme } from '@mui/material';
import { useSnackbar } from 'notistack';

import { ImageInfoProps } from '@components/Page/types';
import { useTranslation } from '@utils';

import { gridImageInfoStyles, listImageInfoStyles } from './styles';

/**
 * Truncates a URL for display
 * Shows beginning and end of URL, replacing the middle with ellipsis
 */
const truncateUrl = (url: string, length: number = 40): string => {
  if (url.length <= length) {
    return url;
  }
  return `${url.substring(0, length / 2)}...${url.substring(url.length - length / 2)}`;
};

/**
 * Determines URL type and returns user-friendly display text
 */
const getFriendlyUrlDisplay = (url: string): { text: string; tooltip: string } => {
  if (url.startsWith('data:')) {
    return {
      text: 'Embedded image data',
      tooltip: 'This image contains embedded data, not a link to an external resource',
    };
  }

  if (url.startsWith('blob:')) {
    return {
      text: 'Temporary image URL',
      tooltip: 'This is a temporary URL generated by the browser',
    };
  }

  if (url.startsWith('file:')) {
    return {
      text: 'Local file',
      tooltip: url,
    };
  }

  return {
    text: truncateUrl(url),
    tooltip: url,
  };
};

/**
 * Component for displaying information about an image (filename, dimensions)
 */
export const ImageInfo = memo(({ fileName, width, height, src, isListMode }: ImageInfoProps) => {
  const theme = useTheme();
  const { enqueueSnackbar } = useSnackbar();
  const { t } = useTranslation();

  const handleDownload = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();

      // Use chrome.downloads API for all URL types
      if (chrome.downloads && chrome.downloads.download) {
        chrome.downloads.download(
          {
            url: src,
            filename: fileName,
            saveAs: false,
          },
          (_) => {
            if (chrome.runtime.lastError) {
              console.error('Download error:', chrome.runtime.lastError);
              enqueueSnackbar(t('download_error_text'), {
                variant: 'error',
                autoHideDuration: 2000,
              });
            } else {
              enqueueSnackbar(t('download_started_text'), {
                variant: 'success',
                autoHideDuration: 2000,
              });
            }
          },
        );
      } else {
        // Fallback for when chrome.downloads API is not available
        try {
          const a = document.createElement('a');
          a.href = src;
          a.download = fileName;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);

          enqueueSnackbar(t('download_started_text'), {
            variant: 'success',
            autoHideDuration: 2000,
          });
        } catch (error) {
          console.error('Download error:', error);
          enqueueSnackbar(t('download_error_text'), {
            variant: 'error',
            autoHideDuration: 2000,
          });
        }
      }
    },
    [src, fileName, enqueueSnackbar, t],
  );

  const handleCopyUrl = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      navigator.clipboard
        .writeText(src)
        .then(() => {
          enqueueSnackbar(t('url_copied_text'), {
            variant: 'success',
            autoHideDuration: 2000,
          });
        })
        .catch((error) => {
          console.error('Error copying URL', error);
          enqueueSnackbar(t('url_copy_error_text'), {
            variant: 'error',
            autoHideDuration: 2000,
          });
        });
    },
    [src, enqueueSnackbar, t],
  );

  const styles = isListMode ? listImageInfoStyles(theme) : gridImageInfoStyles(theme);
  const dimensions = width && height ? `${width} × ${height}` : '';
  const urlDisplay = getFriendlyUrlDisplay(src);
  const canOpenExternally = !src.startsWith('data:') && !src.startsWith('blob:');

  return (
    <Box sx={styles}>
      <Typography className="file-name" variant="body1" title={fileName}>
        {fileName}
      </Typography>

      {dimensions && (
        <Typography component="div" className="dimensions">
          {dimensions}
        </Typography>
      )}

      {isListMode && (
        <>
          <Box className="actions-container">
            <Tooltip title={t('download_image_tooltip')}>
              <IconButton size="small" onClick={handleDownload} className="action-button">
                <FileDownloadIcon fontSize="small" />
              </IconButton>
            </Tooltip>

            <Tooltip title={t('copy_url_tooltip')}>
              <IconButton size="small" onClick={handleCopyUrl} className="action-button">
                <ContentCopyIcon fontSize="small" />
              </IconButton>
            </Tooltip>
          </Box>

          <Box className="url-container">
            {canOpenExternally ? (
              <Tooltip title={urlDisplay.tooltip}>
                <a href={src} className="image-url" target="_blank" rel="noopener noreferrer">
                  <OpenInNewIcon className="url-icon" fontSize="small" />
                  <span className="url-text">{urlDisplay.text}</span>
                </a>
              </Tooltip>
            ) : (
              <Tooltip title={urlDisplay.tooltip}>
                <span className="image-url">{urlDisplay.text}</span>
              </Tooltip>
            )}
          </Box>
        </>
      )}

      {!isListMode && (
        <Tooltip title={t('copy_url_tooltip')}>
          <IconButton size="small" onClick={handleCopyUrl} className="copy-button">
            <ContentCopyIcon fontSize="small" />
          </IconButton>
        </Tooltip>
      )}
    </Box>
  );
});

ImageInfo.displayName = 'ImageInfo';
