/**
 * Truncates a URL for display
 * Shows beginning and end of URL, replacing the middle with ellipsis
 */
export const truncateUrl = (url: string, length: number = 40): string => {
  if (url.length <= length) {
    return url;
  }
  return `${url.substring(0, length / 2)}...${url.substring(url.length - length / 2)}`;
};

/**
 * Get file extension in uppercase format for display
 * @param fileName File name or path
 * @returns File extension in uppercase (PNG by default if extension not found)
 */
export const getFileExtension = (fileName: string): string => {
  // Всегда возвращаем PNG для файлов без расширения
  const extension = fileName.split('.').pop()?.toLowerCase();
  return extension && extension !== fileName.toLowerCase() ? extension.toUpperCase() : 'PNG';
};

/**
 * Determines URL type and returns user-friendly display text
 */
export const getFriendlyUrlDisplay = (url: string): { text: string; tooltip: string } => {
  if (url.startsWith('data:')) {
    return {
      text: 'Embedded image data',
      tooltip: 'This image contains embedded data, not a link to an external resource',
    };
  }

  if (url.startsWith('blob:')) {
    return {
      text: 'Temporary image URL',
      tooltip: 'This is a temporary URL generated by the browser',
    };
  }

  if (url.startsWith('file:')) {
    return {
      text: 'Local file',
      tooltip: url,
    };
  }

  return {
    text: truncateUrl(url),
    tooltip: url,
  };
}; 